site_name: UrbanOPT Documentation

theme: 
  name: material
  palette:
  - scheme: default
    primary: blue-grey
    accent: green
    toggle:
      icon: material/brightness-7 
      name: Switch to dark mode
  - scheme: slate
    primary: blue-grey
    accent: green
    toggle:
      icon: material/brightness-4
      name: Switch to light mode

plugins: 
  - mkdocstrings
  
nav: 
  - Getting Started: index.md
  - Tutorials:
      - Tutorial 1: tutorial_1.md
      - Tutorial 2: tutorial_2.md
  - API Reference: api_reference.md